### ISSUE TITLE
Updating the kubeedge docs

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/website#189]
Now we have lots of new features, we need add more docs for them.

**Comment by sayantan1413** [comment]
Hey, @fisherxu I would like to contribute to this issue. I am well versed with Html, CSS, Javascript, Golang. Can you guide me on how can I get started on this issue?

**Comment by Kodalien** [comment]
@fisherxu  assign to me

**Comment by aastha01chauhan** [comment]
@fisherxu Hi! The really liked the concept of CNCF - Kubernetes SIG Network. I am proficient in python programming and Go. Would love to engage with the community and contribute to this project this spring.

**Comment by Dabjazz** [comment]
@fisherxu  Hi, The kubeedge website is running very well, Now as per my intuition the docs need to be a bit verbose about the dependencies and installation. I would like to suggest some ideas regarding that. I need your approval before suggesting. I have communicated the same in the slack group. Please take a look.

**Comment by Kodalien** [comment]
original robot ! 😅 sorry

**Comment by nilisha-jais** [comment]
@fisherxu can you please elaborate on the issue and discuss further.
