### ISSUE TITLE
Re-design the website 

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/website#292]
Re-design the website, we will need more readable documentation, covering user cases, developer courses, etc.

**Comment by PradyumnaKrishna** [comment]
Hey @fisherxu!

I have good experience in web development, and I would like to work on this as a LFx mentee.
Please provide me some more information and resources to get started, it will help me a lot.

**Comment by kayceeDev** [comment]
@fisherxu @Shelley-BaoYue, I have a solid experience in web development technologies. I also have good experience in writing markdown syntax. I am an active contributor or the layer5.io cloud native community. I will like to take this up as an LFX mentee.

**Comment by Asmit2952** [comment]
Hey, I am interested in working on this issue for LFX Mentorship 2023!

**Comment by Rishikavishnoi** [comment]
@fisherxu I am interested in working on this issue for LFX Mentorship as I  have a great understanding of web development technologies so provide guidance to get started.

**Comment by jakada01** [comment]
I have strong background in web app development. I would like to work on this project for  2023 LFX Mentroship session.

**Comment by akshatvirmani** [comment]
Hi! I am interested in working on this issue under LFX Mentorship!

**Comment by YashKamboj** [comment]
Hey, I am interested in working and contribute on this issue for LFX Mentorship 2023!

**Comment by rakeshkumarnahak** [comment]
I have good web development experience and am excited to work on this project during the LFX Mentorship program 2023.

**Comment by ConnectBhawna** [comment]
Hi @fisherxu , I am interested in learning about this project and want to work on this project under LFX Mentorship.
Please let me know about any materials or resources that I should learn to get a better understanding of the project and its requirements.

Additionally, I was wondering if there is anything else I can do to get started, such as research and learn about the project from the existing documentation.

**Comment by RajGM** [comment]
Hi @fisherxu 
Can we apply as a mentor for this project as well?

**Comment by Arhell** [comment]
@fisherxu  i can help wish this

**Comment by YashPimple** [comment]
Hello, @fisherxu  upon observing the application of this issue within LFX Mentorship for the upcoming batch, I am highly interested in acquiring knowledge about this project. I am eager to work with LFX Mentorship and would appreciate your guidance in identifying any relevant resources or materials that can facilitate a more comprehensive understanding of the project.

**Comment by GenMech** [comment]
Hey @fisherxu @Shelley-BaoYue, I am looking forward to contribute to KubeEgde and I am applying it under LFX Mentorship. I have submitted my cover letter and Resume on the portal. Please let me know if there are some resources or documentation from where I can have more depth of the project and its requirements.
Thanks You

**Comment by robin025** [comment]
Hi @fisherxu @Shelley-BaoYue  , My name is Robin Singh, I am currently a Graduate student enrolled in Master’s Degree at the University of Massachusetts. I am interested in working on this issue, and I am excited to contribute through the LFX program. 

Moreover, I am eager to participate in this project and will definitely be submitting an application.
