### ISSUE TITLE
[Bugs] - Wrong Numbering for Lists in Many Sections

### ISSUE THREAD

**Issue by krishnasvp** [kubeedge/website#353]
**Describe the bug**
The ordering of list items in many sections across the kubeedge docs repo are wrong which need to be corrected. An example for reproducing of the bug is depicted below (Ref: Screenshot below)

**To Reproduce**
1. Go to 'https://kubeedge.io/docs/subproject/ianvs#architecture'
2. Scroll down after the image and you will see the error

**Expected behavior**
The ordering of lists and items should be corrected.

**Screenshots**

<img width="987" alt="Screenshot 2023-07-29 at 1 07 35 PM" src="https://github.com/kubeedge/website/assets/133650795/760297c2-7c18-4fdf-89b4-827dbfa196df">

**Comment by krishnasvp** [comment]
I would love to work on this :)

**Comment by fisherxu** [comment]
Welcome :)
