### ISSUE TITLE
Bug in Docs Navbar

### ISSUE THREAD

**Issue by coder12git** [kubeedge/website#421]
**Describe the bug**
1. Go to 'https://release-1-14.docs.kubeedge.io/docs/'
2.  Jump from version v1.14 -> v1.13 -> v1.12 -> v1.11
3.  You will find that there will be change in navbar design while jumping from latest to older versions.

**To Reproduce**
- I will fix this bug by making the navbar design for older versions same as latest version ( v1.14)

**Comment by coder12git** [comment]
@fisherxu please let me know, should I work on this bug or not :)

**Comment by fisherxu** [comment]
> @fisherxu please let me know, should I work on this bug or not :)

No need to fix it, thanks, we just changed the framework from v1.13 :)

**Comment by iArchitSharma** [comment]
@fisherxu, if this is fixed, shouldn't this issue be closed?

**Comment by fisherxu** [comment]
Sure, let's close it now.
