### ISSUE TITLE
There seems to be a problem with the formatting in the document

### ISSUE THREAD

**Issue by ty-dc** [kubeedge/website#461]
**Describe the bug**
There seems to be a problem with the formatting in the document

**To Reproduce**
1. Go to [install-with-keadm](https://release-1-15.docs.kubeedge.io/docs/setup/install-with-keadm)
3. Scroll down to the third point of the title「Support Metrics-server in Cloud」

**Expected behavior**
Correct markdown format

**Screenshots**

<img width="1328" alt="image" src="https://github.com/kubeedge/website/assets/101157744/b0f51e70-7c4c-48ca-99d2-294dcfc320b3">

**Comment by Shelley-BaoYue** [comment]
Would you like to help us fix this problem? 😄
