### ISSUE TITLE
Dark mode information is not remembered by the website

### ISSUE THREAD

**Issue by azharakbar** [kubeedge/website#48]
**Describe the bug**
Dark mode information is not remembered by the website

**To Reproduce**
1. Open the webpage
2. Choose dark mode
3. Refresh the page
4. Dark mode is lost and the webpage fallsback to light mode

**Expected behavior**
When user chooses dark mode, then whenever the user comes back to the page, it has to be rendered in dark mode

**Suggestion**
you can use localStorage API of modern browsers to store and retrieve the theme information

``localStorage.setItem('theme', 'dark')``
``localStorage.getItem('theme')``

**Comment by anvithks** [comment]
@azharakbar Thanks for raising this bug. Will you be able to work on this and raise a PR? If yes I will assign the same to you.

**Comment by azharakbar** [comment]
@anvithks sure.. You can assign me this issue

**Comment by anvithks** [comment]
@azharakbar Thank you. I have assigned the issue to you. If you need any help setting up the website locally let me know.

**Comment by azharakbar** [comment]
@anvithks Sure .. Will raise the PR soon

**Comment by azharakbar** [comment]
@anvithks PR raised, pls check once
