### ISSUE TITLE
The link in kubeedge website missed the '.md' suffix

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/website#53]
**Describe the bug**
now the link in kubeedge website missed the '.md' suffix, Ref: [page](https://docs.kubeedge.io/en/latest/getting-started/contribute.html#getting-started)
But in github it works fine, in kubeedge.io missed '.md' , so lead to a 404 in kubeedge.io.
![image](https://user-images.githubusercontent.com/28776356/63254226-f1955980-c2a5-11e9-825a-935dbad85c08.png)

Noticed have a PR before related to this. #[704](https://github.com/kubeedge/kubeedge/pull/704)

**Expected behavior**
The link works fine.

/cc @anvithks @yamt Could you please help take a look?

**Comment by yamt** [comment]
it seems it was broken by https://github.com/kubeedge/kubeedge/pull/894

**Comment by fisherxu** [comment]
@yamt Thanks for your suggestion, I think we can have a try to revert that lines(contain .md) change.

**Comment by fisherxu** [comment]
@yamt Have fixed, thanks for your help!
