### ISSUE TITLE
Sync the v1.10~v1.15 and v1.17 changelog(what's new part) to the blog

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/website#531]
Now in blog, https://kubeedge.io/blog, we have no introduction for v1.10~v1.15 and v1.17, so plz sync them from the changelog(what's new part) :)

changelog: https://github.com/kubeedge/kubeedge/tree/master/CHANGELOG
example: https://github.com/kubeedge/website/pull/517

**Comment by 1Shubham7** [comment]
Hey @fisherxu, can I work on this, it look pretty straight forward. In case I miss something, @Catherine-monk, to whome you were assigning this can let me know.

**Comment by fisherxu** [comment]
> Hey @fisherxu, can I work on this, it look pretty straight forward. In case I miss something, @Catherine-monk, to whom you were assigning this can let me know.

@1Shubham7 Sure, just go ahead.
