### ISSUE TITLE
Odd text color in Dark Mode

### ISSUE THREAD

**Issue by iArchitSharma** [kubeedge/website#580]
**Describe the bug**
Text color in Dark mode remains same as it is in light mode, black text in dark background lower its visibilty

**To Reproduce**
1. Go to https://kubeedge.io/
2. Scroll down to Join the Growing Community section

**Expected behavior**
Text color should change to same color used for other headings

**Screenshots**
![image](https://github.com/kubeedge/website/assets/74408634/8532e37c-24a9-43ff-974a-4aefc75c6d74)

**Comment by iArchitSharma** [comment]
If this is a valid issue, I would love to work on this

**Comment by Shelley-BaoYue** [comment]
Good idea! Let's go ahead!
