### ISSUE TITLE
Update PR Template to Close the Issue Automatically When PR is Merged

### ISSUE THREAD

**Issue by iArchitSharma** [kubeedge/website#583]
**Is your feature request related to a problem? Please describe.**
One of the problems I see in this project is that, there are a lot of issue which are resolved by merging their corresponding PR but those issues are still open and have to be closed manually

**Describe the solution you'd like**
Simple solution that can fix this from happening is by updating the PR template with **Closing Keywords**, so that Author has to mention the PR number in description, which will automatically close the issue on merge of the PR
`This PR fixes issue #` - Closing Keywords through which GitHub closes issue automatically

**Comment by wbc6080** [comment]
Sounds good, just go ahead :)

**Comment by iArchitSharma** [comment]
Issue fixed!
