### ISSUE TITLE
Supplemental Developer Contribution Guidelines

### ISSUE THREAD

**Issue by wbc6080** [kubeedge/website#585]
**Is your feature request related to a problem? Please describe.**

At present, some new developers of kubeedge often do not know that DCO signature is required or how to sign when submitting code. At the same time, when developers submit multiple similar commits, they don’t know how to squash multiple commits into one commit like https://github.com/kubeedge/website/pull/532. Therefore, this part of the guide can be supplemented in the contributor document to help new developers better contribute code to the community

**Describe the solution you'd like**

Supplementary developer contribution documentation

**Comment by iArchitSharma** [comment]
@xuemingdi are you still working on this, if not I can take this up

**Comment by xuemingdi** [comment]
@iArchitSharma Thanks for your kindness, I have been working on it.

**Comment by wbc6080** [comment]
Related work have been done.
/close
