### ISSUE TITLE
wrong crd path in  documentation

### ISSUE THREAD

**Issue by EraKin575** [kubeedge/website#605]
**Describe the bug**
it should be : `kubectl apply -f https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1beta1_device.yaml` and
`kubectl apply -f https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1beta1_devicemodel.yaml ` at https://kubeedge.io/docs/setup/install-with-binary

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/0e6a3ce1-025e-4fbe-8ede-f37c8353de73)
![image](https://github.com/user-attachments/assets/bb04e471-3826-443a-a49c-2b0ab5e12da0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Shelley-BaoYue** [comment]
cc @wbc6080

**Comment by wbc6080** [comment]
Thanks for finding this problem. It should be fixed to v1beta1. You can directly submit a PR to fix it. @EraKin575
