### ISSUE TITLE
Request to translation for Korean.

### ISSUE THREAD

**Issue by bluefriday** [kubeedge/website#65]
**Is your feature request related to a problem? Please describe.**

I would like to translate these documents into Korean.

Can only contributors translate documents?

If not, please tell me the procedure to start translating Korean.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kevin-wangzefeng** [comment]
Hi @bluefriday, it is an open community here, so we welcome everyone to contribute.
When you start contributing in any format, you then become contributor :-)

If you are new to projects under CNCF, I'd recommand sign CNCF CLA first, you can find signing insturctions [here](https://github.com/kubernetes/community/blob/master/CLA.md)

The user guide and develper guide are currently located in main repo https://github.com/kubeedge/kubeedge/blob/master/docs, hosted with readthedocs as backend. We don't yet tried any i18n functionalities, may need some investigation.

Other content is under the website repo, which is easy to add Korean support.

**Comment by bluefriday** [comment]
@kevin-wangzefeng 
Thank you for your kindness 👍 
I already signed CNCF CLA. I hope this translation can help many users.
